// DEPRECATED: REFERENCE GR24_CAN REPOSITORY
// #define Configure_Cell_Data 0x64                //Index 0
// #define ACU_Control 0x66                        //Index 2
// #define Battery_Limits 0x67                     //Index 3
// #define ACU_Ping_Request 0x95                   //Index 4
// #define ACU_General 0x96                        //Index 5
// #define ACU_General2 0x97                       //Index 6
// #define Powertrain_Cooling 0x98                 //Index 7
// #define Charging_Cart_Config 0x99               //Index 8
// #define Expanded_Cell_Data 0xA0                 //Index 9
// #define Condensed_Cell_Voltage_n0 0xA1          //Index 10
// #define Condensed_Cell_Voltage_n8 0xA2          //Index 11
// #define Condensed_Cell_Voltage_n16 0xA3         //Index 12
// #define Condensed_Cell_Voltage_n24 0xA4         //Index 13
// #define Condensed_Cell_Voltage_n32 0xA5         //Index 14
// #define Condensed_Cell_Voltage_n40 0xA6         //Index 15
// #define Condensed_Cell_Voltage_n48 0xA7         //Index 16
// #define Condensed_Cell_Voltage_n56 0xA8         //Index 17
// #define Condensed_Cell_Voltage_n64 0xA9         //Index 18
// #define Condensed_Cell_Voltage_n72 0xAA         //Index 19
// #define Condensed_Cell_Voltage_n80 0xAB         //Index 20
// #define Condensed_Cell_Voltage_n88 0xAC         //Index 21
// #define Condensed_Cell_Voltage_n96 0xAD         //Index 22
// #define Condensed_Cell_Voltage_n104 0xAE        //Index 23
// #define Condensed_Cell_Voltage_n112 0xAF        //Index 24
// #define Condensed_Cell_Voltage_n120 0xB0        //Index 25
// #define Condensed_Cell_Voltage_n128 0xB1        //Index 26
// #define Condensed_Cell_Voltage_n136 0xB2        //Index 27
// #define Condensed_Cell_Temp_n0 0xB3             //Index 28
// #define Condensed_Cell_Temp_n8 0xB4             //Index 29
// #define Condensed_Cell_Temp_n16 0xB5            //Index 30
// #define Condensed_Cell_Temp_n24 0xB6            //Index 31
// #define Condensed_Cell_Temp_n32 0xB7            //Index 32
// #define Condensed_Cell_Temp_n40 0xB8            //Index 33
// #define Condensed_Cell_Temp_n48 0xB9            //Index 34
// #define Condensed_Cell_Temp_n56 0xBA            //Index 35
// #define Condensed_Cell_Temp_n64 0xBB            //Index 36
// #define Condensed_Cell_Temp_n72 0xBC            //Index 37
// #define Condensed_Cell_Temp_n80 0xBD            //Index 38
// #define Condensed_Cell_Temp_n88 0xBE            //Index 39
// #define Condensed_Cell_Temp_n96 0xBF            //Index 40
// #define Condensed_Cell_Temp_n104 0xC0           //Index 41
// #define Condensed_Cell_Temp_n112 0xC1           //Index 42
// #define Condensed_Cell_Temp_n120 0xC2           //Index 43
// #define Condensed_Cell_Temp_n128 0xC3           //Index 44
// #define Condensed_Cell_Temp_n134 0xC4           //Index 45
// #define ACU_Ping_Response 0xC7                  //Index 46
// #define Pedals_Inputs 0xC8                      //Index 47
// #define Pedals_Ping_Response 0xC9               //Index 48
// #define Pedals_Ping_Request 0xCA                //Index 49
// #define VDM_States 0xF0                         //Index 50
// #define VDM_Errors 0xF1                         //Index 51
// #define VDM_Ping_Values 0xF2                    //Index 52
// #define VDM_States_and_Settings 0xF3            //Index 53


// #define Energy_Meter_Measurements 0x100         //Index 58
// #define DTI_Control_1 0x116                     //Index 59
// #define DTI_Control_2 0x216                     //Index 60
// #define DTI_Control_3 0x316                     //Index 61
// #define STUFFFFFF 0x400                         //Index 62
// #define DTI_Control_4 0x416                     //Index 63
// #define DTI_Control_5 0x516                     //Index 64
// #define DTI_Control_6 0x616                     //Index 65
// #define DTI_Control_7 0x716                     //Index 66
// //#define Energy_Meter_Reserved 0x7E7             //Index 67
// //#define Energy_Meter_Reserved 0x7EF             //Index 68
// #define DTI_Control_8 0x816                     //Index 69
// #define DTI_Control_9 0x916                     //Index 70
// #define DTI_Control_10 0xA16                    //Index 71
// #define DTI_Control_11 0xB16                    //Index 72
// #define DTI_Control_12 0xC16                    //Index 73
// #define DTI_Data_1 0x2016                       //Index 74
// #define DTI_Data_2 0x2116                       //Index 75
// #define DTI_Data_3 0x2216                       //Index 76
// #define DTI_Data_4 0x2316                       //Index 77
// #define DTI_Data_5 0x2416                       //Index 78
// #define BCM_Ping_Request 0x10EFE                //Index 79
// #define BCM_Ping_Response 0x10EFF               //Index 80
// //BCM Stuff
// #define Steering_Wheel_Ping_Request 0x10FFE     //Index 109
// #define Steering_Wheel_Ping_Response 0x10FFF    //Index 110
// //#define Steering_Accel 0x11000                  //Index 111
// //#define Steering_Gyro 0x11000                   //Index 112
// #define Data_to_VDM 0x11002                     //Index 113
// #define TCM_Status 0x12000                      //Index 114
// #define Dash_Panel_Ping_Request 0x12FFE         //Index 115
// #define Dash_Panel_Ping_Response 0x12FFF        //Index 116
// #define Button_Event 0x13000                    //Index 117
// #define LED_Outputs 0x13001                     //Index 118
// #define Charging_SDC_Ping_Request 0x14000       //Index 119
// #define Charging_SDC_Ping_Response 0x14001      //Index 120
// #define Charging_SDC_States 0x14002             //Index 121
// #define Charger_Data 0x18FF50E5                 //Index 122
// #define Charger_Control 0x1806E5F4              //Index 123